#### Page Classifier Model ####
#type: weka
#parameters:
#  features_file: pageclassifier.features
#  model_file: pageclassifier.model
#### Regex Filters ####  
type: regex
parameters:
    boolean_operator: "OR"
#    url:
#      boolean_operator: "OR"
#      regexes:
#        - .*category=1.*
#        - .*post\.php.*
    title:
#      boolean_operator: "OR"
      regexes:
        - .*Tour de France.*
    content:
#      boolean_operator: "OR"
      regexes:
        - .*Tour de France.*        